// Auto-generated by scripts/detectDeltaFixtures.mjs
// Source: ver0_1.png -> ver2_1.png
// Run: node scripts/detectDeltaFixtures.mjs --base <base.png> --target <target.png>

export type DetectedFixtureKind = 'bookshelf' | 'counter' | 'displayLow'

export type DetectedFixture = {
  kind: DetectedFixtureKind
  cx: number
  cz: number
  w: number
  d: number
  yaw: number
  h: number
  score?: number
  sourceClass?: string
}

export const DETECTED_FIXTURE_SOURCE = 'map_info/original.png (processMap; delta TBD)'
export const DETECTED_IMAGE_SIZE = { width: 1477, height: 829 }
export const detectedFixtures: DetectedFixture[] = []
